import { createHash } from "node:crypto";

import { describe, expect, it, vi } from "vitest";

import { createPlaceholderThumbnail } from "../../src/lib/images/thumbnails.ts";
import {
  CURRENT_PLACEHOLDER_SHA256,
  PlaceholderRepairError,
  assertSafeApplyTarget,
  createCurrentPlaceholderBuffer,
  createSupabaseRepository,
  executePlaceholderRepair,
  parseArguments,
  targetConfiguration,
} from "../../scripts/reclassify-placeholder-thumbnails.mjs";

const FIRST_ID = "00000000-0000-4000-8000-000000000001";
const SECOND_ID = "00000000-0000-4000-8000-000000000002";

function candidate(id = FIRST_ID, path = `${FIRST_ID}/workflow-attempt.webp`) {
  return { id, thumbnail_origin: "automatic", thumbnail_path: path };
}

function downloadable(buffer) {
  return {
    size: buffer.byteLength,
    async arrayBuffer() {
      return buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);
    },
  };
}

describe("placeholder repair fingerprint", () => {
  it("stays byte-identical to the placeholder generated by the application", async () => {
    const [operatorBuffer, applicationThumbnail] = await Promise.all([
      createCurrentPlaceholderBuffer(),
      createPlaceholderThumbnail(),
    ]);

    expect(operatorBuffer.equals(applicationThumbnail.buffer)).toBe(true);
    expect(createHash("sha256").update(operatorBuffer).digest("hex")).toBe(
      CURRENT_PLACEHOLDER_SHA256,
    );
    expect(createHash("sha256").update(applicationThumbnail.buffer).digest("hex")).toBe(
      CURRENT_PLACEHOLDER_SHA256,
    );
  });
});

describe("placeholder repair CLI safety", () => {
  it("defaults to a dry run with a bounded scan", () => {
    expect(parseArguments([])).toEqual({
      apply: false,
      confirmHost: null,
      help: false,
      limit: 1_000,
    });
  });

  it("requires an exact host confirmation for every apply", () => {
    const target = new URL("https://project.supabase.co");
    const options = parseArguments(["--apply"]);

    expect(() => assertSafeApplyTarget(target, options, {})).toThrowError(
      expect.objectContaining({ code: "PLACEHOLDER_REPAIR_HOST_CONFIRMATION_REQUIRED" }),
    );
    expect(() =>
      assertSafeApplyTarget(target, { ...options, confirmHost: "project.supabase.co" }, {}),
    ).not.toThrow();
    expect(() =>
      assertSafeApplyTarget(
        new URL("http://127.0.0.1:54321"),
        { ...options, confirmHost: "127.0.0.1" },
        {},
      ),
    ).not.toThrow();
  });

  it("forbids apply in automation and does not accept confirmation in dry-run mode", () => {
    expect(() => parseArguments(["--confirm-host", "project.supabase.co"])).toThrowError(
      expect.objectContaining({ code: "PLACEHOLDER_REPAIR_CONFIRMATION_WITHOUT_APPLY" }),
    );
    expect(() =>
      assertSafeApplyTarget(
        new URL("https://project.supabase.co"),
        parseArguments(["--apply", "--confirm-host", "project.supabase.co"]),
        { CI: "true" },
      ),
    ).toThrowError(
      expect.objectContaining({ code: "PLACEHOLDER_REPAIR_APPLY_FORBIDDEN_IN_AUTOMATION" }),
    );
  });

  it("uses dedicated credentials and keeps errors opaque", () => {
    expect(
      targetConfiguration({
        CURIO_PLACEHOLDER_REPAIR_SERVICE_ROLE_KEY: "secret-value",
        CURIO_PLACEHOLDER_REPAIR_SUPABASE_URL: "https://project.supabase.co",
      }).target.origin,
    ).toBe("https://project.supabase.co");
    expect(() =>
      targetConfiguration({
        NEXT_PUBLIC_SUPABASE_URL: "https://fallback.supabase.co",
        SUPABASE_SERVICE_ROLE_KEY: "fallback-secret",
      }),
    ).toThrowError(expect.objectContaining({ code: "PLACEHOLDER_REPAIR_CREDENTIALS_REQUIRED" }));
    expect(() =>
      targetConfiguration({
        CURIO_PLACEHOLDER_REPAIR_SERVICE_ROLE_KEY: "secret-value",
        CURIO_PLACEHOLDER_REPAIR_SUPABASE_URL: "http://remote.example.test",
      }),
    ).toThrowError(expect.objectContaining({ code: "PLACEHOLDER_REPAIR_TARGET_INVALID" }));
    expect(new PlaceholderRepairError("PLACEHOLDER_REPAIR_TEST").message).toBe(
      "PLACEHOLDER_REPAIR_TEST",
    );
  });
});

describe("placeholder repair execution", () => {
  it("only plans byte-identical placeholders during the default dry run", async () => {
    const placeholder = Buffer.from("exact-placeholder");
    const reclassify = vi.fn();
    const repository = {
      listCandidates: vi
        .fn()
        .mockResolvedValue([
          candidate(),
          candidate(SECOND_ID, `${SECOND_ID}/workflow-attempt.webp`),
        ]),
      downloadObject: vi
        .fn()
        .mockResolvedValueOnce(downloadable(placeholder))
        .mockResolvedValueOnce(downloadable(Buffer.from("real-preview"))),
      reclassify,
    };

    await expect(
      executePlaceholderRepair(repository, { placeholderBuffer: placeholder }),
    ).resolves.toEqual({ matched: 1, notMatched: 1, scanned: 2, updated: 0 });
    expect(reclassify).not.toHaveBeenCalled();
  });

  it("reclassifies only exact matches and is idempotent", async () => {
    const placeholder = Buffer.from("exact-placeholder");
    const rows = [candidate()];
    const repository = {
      listCandidates: vi.fn(async () => rows.filter((row) => row.thumbnail_origin === "automatic")),
      downloadObject: vi.fn(async () => downloadable(placeholder)),
      reclassify: vi.fn(async (match) => {
        const row = rows.find(
          (item) => item.id === match.id && item.thumbnail_path === match.thumbnailPath,
        );
        if (!row || row.thumbnail_origin !== "automatic") throw new Error("guard failed");
        row.thumbnail_origin = "placeholder";
      }),
    };

    await expect(
      executePlaceholderRepair(repository, { apply: true, placeholderBuffer: placeholder }),
    ).resolves.toEqual({ matched: 1, notMatched: 0, scanned: 1, updated: 1 });
    await expect(
      executePlaceholderRepair(repository, { apply: true, placeholderBuffer: placeholder }),
    ).resolves.toEqual({ matched: 0, notMatched: 0, scanned: 0, updated: 0 });
  });

  it("fails before writes on duplicate object paths or download errors", async () => {
    const sharedPath = `${FIRST_ID}/shared.webp`;
    const collisionRepository = {
      listCandidates: vi
        .fn()
        .mockResolvedValue([candidate(FIRST_ID, sharedPath), candidate(FIRST_ID, sharedPath)]),
      downloadObject: vi.fn(),
      reclassify: vi.fn(),
    };
    await expect(
      executePlaceholderRepair(collisionRepository, {
        apply: true,
        placeholderBuffer: Buffer.from("placeholder"),
      }),
    ).rejects.toMatchObject({ code: "PLACEHOLDER_REPAIR_CANDIDATE_COLLISION" });
    expect(collisionRepository.downloadObject).not.toHaveBeenCalled();
    expect(collisionRepository.reclassify).not.toHaveBeenCalled();

    const downloadRepository = {
      listCandidates: vi.fn().mockResolvedValue([candidate()]),
      downloadObject: vi.fn().mockRejectedValue(new Error("private object detail")),
      reclassify: vi.fn(),
    };
    await expect(
      executePlaceholderRepair(downloadRepository, {
        apply: true,
        placeholderBuffer: Buffer.from("placeholder"),
      }),
    ).rejects.toThrow("private object detail");
    expect(downloadRepository.reclassify).not.toHaveBeenCalled();
  });

  it("rejects an object path outside the candidate entry folder", async () => {
    const repository = {
      listCandidates: vi
        .fn()
        .mockResolvedValue([candidate(FIRST_ID, `${SECOND_ID}/workflow-attempt.webp`)]),
      downloadObject: vi.fn(),
      reclassify: vi.fn(),
    };

    await expect(
      executePlaceholderRepair(repository, { placeholderBuffer: Buffer.from("placeholder") }),
    ).rejects.toMatchObject({ code: "PLACEHOLDER_REPAIR_CANDIDATE_INVALID" });
    expect(repository.downloadObject).not.toHaveBeenCalled();
  });

  it("fails closed if a mocked SHA-256 collision is not byte-identical", async () => {
    const repository = {
      listCandidates: vi.fn().mockResolvedValue([candidate()]),
      downloadObject: vi.fn().mockResolvedValue(downloadable(Buffer.from("different-contents"))),
      reclassify: vi.fn(),
    };
    const forcedDigest = Buffer.alloc(32, 7);

    await expect(
      executePlaceholderRepair(repository, {
        apply: true,
        hashBuffer: () => forcedDigest,
        placeholderBuffer: Buffer.from("exact-placeholder"),
      }),
    ).rejects.toMatchObject({ code: "PLACEHOLDER_REPAIR_HASH_COLLISION" });
    expect(repository.reclassify).not.toHaveBeenCalled();
  });
});

describe("placeholder repair Supabase repository", () => {
  it("lists only automatic entries with a non-null path", async () => {
    const query = {
      eq: vi.fn(),
      not: vi.fn(),
      order: vi.fn(),
      range: vi.fn().mockResolvedValue({ data: [candidate()], error: null }),
      select: vi.fn(),
    };
    query.select.mockReturnValue(query);
    query.eq.mockReturnValue(query);
    query.not.mockReturnValue(query);
    query.order.mockReturnValue(query);
    const client = { from: vi.fn().mockReturnValue(query) };

    await expect(createSupabaseRepository(client).listCandidates(10)).resolves.toEqual([
      candidate(),
    ]);
    expect(query.eq).toHaveBeenCalledWith("thumbnail_origin", "automatic");
    expect(query.not).toHaveBeenCalledWith("thumbnail_path", "is", null);
  });

  it("guards every update by id, old origin and exact object path", async () => {
    const row = candidate();
    const query = {
      eq: vi.fn(),
      select: vi.fn().mockResolvedValue({
        data: [{ ...row, thumbnail_origin: "placeholder" }],
        error: null,
      }),
      update: vi.fn(),
    };
    query.update.mockReturnValue(query);
    query.eq.mockReturnValue(query);
    const client = { from: vi.fn().mockReturnValue(query) };

    await createSupabaseRepository(client).reclassify({
      id: row.id,
      thumbnailPath: row.thumbnail_path,
    });

    expect(query.update).toHaveBeenCalledWith({ thumbnail_origin: "placeholder" });
    expect(query.eq).toHaveBeenNthCalledWith(1, "id", row.id);
    expect(query.eq).toHaveBeenNthCalledWith(2, "thumbnail_origin", "automatic");
    expect(query.eq).toHaveBeenNthCalledWith(3, "thumbnail_path", row.thumbnail_path);
  });
});
